import type {
  ArenaEvent,
  BotInstance,
  Candle,
  ExecutionFill,
  OrderIntent,
  PortfolioSnapshot,
  SimulationConfig,
} from "./types.ts";
import type { ExecutionResult } from "./execution.ts";
import type {
  BrokerEventEnvelope,
  BrokerReconciliationResult,
} from "./brokerTypes.ts";

// ─── Adapter Mode Discriminants ──────────────────────────────────────────────

/**
 * The backtest simulation loop only ever uses a synchronous simulation adapter.
 * Paper and live modes belong to separate async session runners, never to
 * `createSimulation()`.
 */
export type SimulationAdapterMode = "simulation";

/**
 * Broker-connected session runners use "paper" or "live" modes.
 * These never enter the synchronous replay loop.
 */
export type BrokerAdapterMode = "paper" | "live";

/** Union of all adapter modes — for logging and UI display only. */
export type AdapterMode = SimulationAdapterMode | BrokerAdapterMode;

// ─── SimulationExecutionAdapter ───────────────────────────────────────────────

/**
 * Synchronous execution adapter for the deterministic backtest simulation loop.
 *
 * Used exclusively by `createSimulation()`. Produces fills synchronously at
 * candle-close price ± slippage. Never connects to external services.
 *
 * Strategies remain completely unaware of which adapter is active — they emit
 * broker-neutral `OrderIntent` objects and never touch this interface.
 *
 * This is intentionally kept sync. Async complexity (partial fills, delayed
 * confirmations, reconnects) belongs in the broker session runners (M7+),
 * not here.
 */
export interface SimulationExecutionAdapter {
  readonly mode: SimulationAdapterMode;

  execute(
    intent: OrderIntent,
    bot: BotInstance,
    portfolio: PortfolioSnapshot,
    candle: Candle,
    config: SimulationConfig,
  ): ExecutionResult;
}

// ─── OrderExecutionContext ────────────────────────────────────────────────────

/**
 * Per-order attribution context passed to `BrokerAdapter.executeAsync()`.
 *
 * `botId` identifies which sleeve's fill this belongs to (for audit and
 * governance stat tracking). `clientOrderId` is a UUID generated by the
 * session runner before submission; in M12+ it will be sent as
 * `client_order_id` to Alpaca for idempotent fill attribution via the
 * trade_updates WebSocket stream.
 */
export interface OrderExecutionContext {
  /** The bot that submitted this intent. */
  botId: string;
  /** Caller-generated UUID for idempotent broker-side attribution (M12+). */
  clientOrderId: string;
}

// ─── BrokerAdapter ────────────────────────────────────────────────────────────

/**
 * Async execution adapter for broker-connected paper and live session runners.
 *
 * NOT used by `createSimulation()` — this belongs to the separate
 * `PaperSessionRunner` / `LiveSessionRunner` (Milestone 7+).
 *
 * Design intent:
 *   - Orders are submitted to a broker and fills arrive asynchronously
 *     (Alpaca WebSocket stream or polling).
 *   - The session runner awaits `executeAsync()` before advancing to the next
 *     decision cycle.
 *   - Partial fills, reconnects, cancel/replace flows, and account drift
 *     are all concerns of this layer — not the simulation loop.
 *
 * Implementations throw `NOT_IMPLEMENTED` in the M6 spike; all methods are
 * implemented in Milestone 7+ once the session runner is designed.
 */
export interface BrokerAdapter {
  readonly mode: BrokerAdapterMode;

  /**
   * Submit an order intent to the broker and await the resulting fill.
   * The session runner must not advance the decision cycle until this resolves.
   * Implementations are responsible for gate checks, symbol allowlist
   * validation, and disarming the gate on broker errors.
   *
   * `context.botId` is used for fill attribution; `context.clientOrderId`
   * is a caller-generated UUID reserved for M12+ Alpaca idempotency.
   * Simulated implementations may ignore the context entirely.
   */
  executeAsync(
    intent: OrderIntent,
    portfolio: PortfolioSnapshot,
    context: OrderExecutionContext,
  ): Promise<ExecutionFill>;

  /**
   * Compare the broker's account snapshot against the engine's internal
   * portfolio state. Returns a reconciliation result; if `ok` is false,
   * the caller must disarm the gate and emit a RECONCILIATION_DRIFT event.
   */
  reconcileAccount(
    enginePortfolio: PortfolioSnapshot,
  ): Promise<BrokerReconciliationResult>;

  /**
   * Translate a raw broker event envelope into an `ArenaEvent` for the
   * session log. The caller emits the event; this method only translates.
   */
  ingestBrokerEvent(envelope: BrokerEventEnvelope): ArenaEvent;
}
